### ISSUE TITLE
关于JSONDecodeError

### ISSUE THREAD

**Issue by xuanxuanQAQ** [PeterH0323/Streamer-Sales#16]
您好，我在autodl根据readme中逐步进行部署了本项目，但出现了如下错误，我想知道是我哪里做错了吗

(streamer-sales) root@autodl-container-42a44688ad-66cc3830:~/autodl-tmp/Streamer-Sales# streamlit run app.py --server.address=0.0.0.0 --server.port 7860

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.

  You can now view your Streamlit app in your browser.

  URL: http://0.0.0.0:7860

Starting...
2024-07-18 11:31:01.034 Uncaught app exception
Traceback (most recent call last):
  File "/root/miniconda3/envs/streamer-sales/lib/python3.10/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/root/miniconda3/envs/streamer-sales/lib/python3.10/site-packages/simplejson/__init__.py", line 514, in loads
    return _default_decoder.decode(s)
  File "/root/miniconda3/envs/streamer-sales/lib/python3.10/site-packages/simplejson/decoder.py", line 386, in decode
    obj, end = self.raw_decode(s)
  File "/root/miniconda3/envs/streamer-sales/lib/python3.10/site-packages/simplejson/decoder.py", line 416, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/streamer-sales/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/root/autodl-tmp/Streamer-Sales/app.py", line 488, in <module>
    main()
  File "/root/autodl-tmp/Streamer-Sales/app.py", line 318, in main
    init_tts()
  File "/root/autodl-tmp/Streamer-Sales/app.py", line 264, in init_tts
    st.session_state.gen_tts_checkbox = get_server_plugins_info_api()['tts']
  File "/root/autodl-tmp/Streamer-Sales/utils/api.py", line 149, in get_server_plugins_info_api
    res = requests.get(API_CONFIG.PLUGINS_INFO_URL).json()
  File "/root/miniconda3/envs/streamer-sales/lib/python3.10/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PeterH0323** [comment]
目前有两种部署方式：https://github.com/PeterH0323/Streamer-Sales?tab=readme-ov-file#%E6%9C%AC%E5%9C%B0

如果您想直接使用  streamlit 启动前后融合版本的应用，需要切换 v0.7.1 tag：

```bash

git checkout v0.7.1

# Agent Key (如果没有请忽略)
export DELIVERY_TIME_API_KEY="${快递 EBusinessID},${快递 api_key}"
export WEATHER_API_KEY="${天气 API key}"

streamlit run app.py --server.address=0.0.0.0 --server.port 7860
```
